const actionTypes = {
  'ADD_TO_CART': 'ADD_TO_CART',
  'REMOVE_FROM_CART': 'REMOVE_FROM_CART',
  'PRODUCTS_LOADING': 'PRODUCTS_LOADING', 
  'PRODUCTS_SUCCESS': 'PRODUCTS_SUCCESS', 
  'PRODUCTS_FAILURE': 'PRODUCTS_FAILURE',
  'CREATING_PRODUCT': 'CREATING_PRODUCT',
  'CREATE_PRODUCT_RESPONSE': 'CREATE_PRODUCT_RESPONSE'
};

export default actionTypes;
